import React, { useEffect, useState } from 'react';
import { api } from '../services/api';
import { Recommendation } from '../types';
import { Badge } from '../components/common/Badge';
import { WhyPanelModal } from '../components/advisory/WhyPanelModal';
import { Clock, HelpCircle, History } from 'lucide-react';

export const HistoryPage: React.FC = () => {
  const [history, setHistory] = useState<Recommendation[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedRec, setSelectedRec] = useState<Recommendation | null>(null);

  useEffect(() => {
    fetchHistory();
  }, []);

  const fetchHistory = async () => {
    try {
      setLoading(true);
      const data = await api.getRecommendationHistory();
      setHistory(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6 font-sans">
      <div>
        <h1 className="text-2xl font-extrabold text-[#0F291E]">Recommendation History</h1>
        <p className="text-xs text-stone-500 mt-1">
          Historical audit trail preserving rule IDs, versions, rule status, feasibility scores, and costs generated by CropCompass.
        </p>
      </div>

      {loading ? (
        <div className="text-center py-12 text-stone-400 text-sm">Loading recommendation history...</div>
      ) : history.length === 0 ? (
        <div className="bg-white rounded-2xl border border-stone-200 p-12 text-center my-8">
          <div className="w-12 h-12 rounded-full bg-stone-100 flex items-center justify-center text-stone-400 mx-auto mb-3">
            <History className="w-6 h-6" />
          </div>
          <h3 className="text-base font-bold text-stone-800">No recommendation history yet</h3>
          <p className="text-xs text-stone-500 mt-1 max-w-sm mx-auto">
            Generate advisory recommendations from the Advisory page to record historical decisions.
          </p>
        </div>
      ) : (
        <div className="bg-white rounded-2xl border border-stone-200/80 shadow-xs overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-[#FAF8F5] border-b border-stone-200 text-stone-600 font-bold uppercase tracking-wider">
                <tr>
                  <th className="px-6 py-4">Timestamp</th>
                  <th className="px-6 py-4">Farmer ID</th>
                  <th className="px-6 py-4">Rule & Version</th>
                  <th className="px-6 py-4">Rule Status</th>
                  <th className="px-6 py-4">Feasibility</th>
                  <th className="px-6 py-4">Cost (₹)</th>
                  <th className="px-6 py-4 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-stone-100 text-stone-800 font-medium">
                {history.map((item) => (
                  <tr key={item.id} className="hover:bg-stone-50 transition">
                    <td className="px-6 py-4 text-stone-500">
                      {new Date(item.created_at).toLocaleString()}
                    </td>
                    <td className="px-6 py-4 font-bold text-stone-900">
                      {item.farmer_id}
                    </td>
                    <td className="px-6 py-4">
                      <span className="font-semibold text-emerald-800">{item.rule_id}</span>
                      <span className="text-stone-400 text-[10px] ml-1">v{item.rule_version}</span>
                    </td>
                    <td className="px-6 py-4">
                      <Badge type={item.rule_status === 'APPROVED' ? 'approved' : 'custom'} text={item.rule_status} />
                    </td>
                    <td className="px-6 py-4">
                      <Badge
                        type={
                          item.feasibility_status === 'HIGHLY_FEASIBLE' ? 'feasible' :
                          item.feasibility_status === 'PARTIALLY_FEASIBLE' ? 'partial' : 'not_feasible'
                        }
                      />
                    </td>
                    <td className="px-6 py-4 font-bold text-stone-900">
                      ₹{item.estimated_cost?.toLocaleString()}
                    </td>
                    <td className="px-6 py-4 text-right">
                      <button
                        onClick={() => setSelectedRec(item)}
                        className="px-3 py-1.5 bg-stone-100 hover:bg-stone-200 text-stone-800 font-bold rounded-lg text-xs transition inline-flex items-center gap-1"
                      >
                        <HelpCircle className="w-3.5 h-3.5 text-stone-600" /> Breakdown
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Why Modal */}
      <WhyPanelModal
        isOpen={Boolean(selectedRec)}
        recommendation={selectedRec}
        onClose={() => setSelectedRec(null)}
      />
    </div>
  );
};
